version: "3"

services:
  mysqldb:
      image: mysql:8.0
      container_name: mysqlcontainer
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
      ports:
        - 3336:3306
      expose:
        - 3306
      environment:
        MYSQL_DATABASE: hackathon_users
        MYSQL_USER: 
        MYSQL_PASSWORD: letmein
        MYSQL_ROOT_PASSWORD: letmein
        SERVICE_NAME: mysqldb
      networks:
        - internalnet

  app:
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - "mysqldb"
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  mysqldb:
    driver: local